# Generated by Django 3.1.5 on 2021-01-13 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('AssessmentID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Assessment_Name', models.CharField(max_length=500)),
                ('Assessment_Desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.CharField(max_length=10, unique=True)),
                ('Course_Name', models.CharField(max_length=500)),
                ('Course_Description', models.TextField(default='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lect_Name', models.CharField(max_length=500)),
                ('Lect_Email', models.EmailField(max_length=254)),
                ('UserID', models.OneToOneField(default='ID Number', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.IntegerField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestID', models.CharField(max_length=10)),
                ('Status', models.BooleanField()),
                ('CourseID', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='student.course')),
                ('Requestor', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='student.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.TextField()),
                ('Answer_1', models.CharField(max_length=500)),
                ('Answer_2', models.CharField(max_length=500)),
                ('Answer_3', models.CharField(max_length=500)),
                ('Answer_4', models.CharField(max_length=500)),
                ('Correct_Answer', models.CharField(choices=[('A', 'AnswerA'), ('B', 'AnswerB'), ('C', 'AnswerC'), ('D', 'AnswerD')], default='A', max_length=1)),
                ('Answer_Explanation', models.TextField()),
                ('AssessmentID', models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='student.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('TopicID', models.AutoField(primary_key=True, serialize=False)),
                ('Topic_No', models.IntegerField()),
                ('Topic_Name', models.CharField(max_length=500)),
                ('CourseID', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='student.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseObjective',
            fields=[
                ('ObjectiveID', models.AutoField(primary_key=True, serialize=False)),
                ('Objective_No', models.CharField(max_length=4)),
                ('Objective_Name', models.CharField(max_length=700)),
                ('CourseID', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='student.course')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassID', models.CharField(max_length=10)),
                ('CourseID', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='student.course')),
                ('Lecturer', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='student.lecturer')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='CourseID',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='student.course'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_Name', models.CharField(max_length=500)),
                ('Admin_Email', models.EmailField(max_length=254)),
                ('UserID', models.OneToOneField(default='ID Number', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
