# Generated by Django 3.1.1 on 2020-11-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.IntegerField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=500)),
            ],
        ),
    ]
