# Generated by Django 3.1.1 on 2020-12-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_class_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_Name', models.CharField(max_length=500)),
                ('Admin_Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('AssessmentID', models.AutoField(primary_key=True, serialize=False)),
                ('Assessment_Name', models.CharField(max_length=500)),
                ('Assessment_Desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseObjective',
            fields=[
                ('ObjectiveID', models.AutoField(primary_key=True, serialize=False)),
                ('Objective_No', models.CharField(max_length=4)),
                ('Objective_Name', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTopic',
            fields=[
                ('TopicID', models.AutoField(primary_key=True, serialize=False)),
                ('Topic_No', models.IntegerField()),
                ('Topic_Name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lect_Name', models.CharField(max_length=500)),
                ('Lect_Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.TextField()),
                ('Answer_1', models.CharField(max_length=500)),
                ('Answer_2', models.CharField(max_length=500)),
                ('Answer_3', models.CharField(max_length=500)),
                ('Answer_4', models.CharField(max_length=500)),
                ('Correct_Answer', models.CharField(choices=[('A', 'AnswerA'), ('B', 'AnswerB'), ('C', 'AnswerC'), ('D', 'AnswerD')], default='A', max_length=1)),
                ('Answer_Explanation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestID', models.CharField(max_length=10)),
                ('Status', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='class',
            name='ClassID',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='CourseID',
            field=models.CharField(max_length=10),
        ),
    ]
