# Generated by Django 3.1.5 on 2021-01-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_question_topics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
