# Generated by Django 3.1.1 on 2020-12-23 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0004_lecturer_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='UserID',
            field=models.ForeignKey(default='ID Number', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
